identifier: id.my.wao.cider-plugin
name: Waoweens' Cider Plugin
description: some personal changes to Cider
author: Waoweens
repo: https://github.com/Waoweens/cider-plugin
entry:
  "plugin.js":
    type: main